/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUY3VlpRSjBzSmxhUk5lQ29YcjR0R1A3b1lQdVRrMFBEbUljV1dqemUwND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaWFHaitzek8xUDdTdlY5Qm5JS3pjN3hDNmFzTCtMMHlNQTJPZ0ZxRWttdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnQWNNZ1o3ZElEeEFaMG9pYlZ1aVF6Y1N1amVDbCtGWC90LzU0VksvQWxVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6VElYWHlUclFTS0hmODF3TTdoSmd2KzBJVWJ4RTFteEcyOElpT2FhUWxvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdDckVLdERSS2d2YUxHNVFjdHZMZDh2QkxrNW5kSDZIUUxMbGZEWmkxMFE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImIrWnZwVkg5VXIxdFhmREZidmcrcFA1RVZtblBrWjlCTEFndTRGZE1ReTg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0xTQzRBRGxTZ1k2cHRGemdoTnJLQktqQ01VQ0hNaW80Q3NleUFDdDJFRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWVA4cEt4bllvdWxVcWtZV2g0TGk0V1pUYkJSN1RDL1Q1d2ZIR3Nkd0luUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdSdzZ1Z0ZPY0Y1WUFySzJCRlJMeGZKeTh6dVMvOS83a1hwc3MxWHdJWU5lcnFRZjNURHpuaCthd1FOY0xiUytOaEVhdENLVXpRaDh3a0pPSUxKTWl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIxLCJhZHZTZWNyZXRLZXkiOiJzbXZZdFo0UXZZQTdKMG1hNXh6Z3dNKzBYNXBHcDF2VFVLa2lDSHg5VDNjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJoXzZkR3k3RFFIT1JQVWRwZUFBY1J3IiwicGhvbmVJZCI6IjI3NTdmMDNlLTE1OTItNGExNi1hZDkyLThjMzkyNzkxNGY2MyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxZWJWckhmbEhWV2c0ZnhEVFdlMFlSVldoeVk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidXVYTkZXWmhKWnFhUWxoRWgyUXBObnJyUnhvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkpKQUFIS05EIiwibWUiOnsiaWQiOiIyMjU4ODE0NTcyMjozNUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSXFqenZrQ0VLMkhvYm9HR0JVZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVkdqL3ZSOFNpKzlSZkpObUVsWUhUeHVTeFRnMERya2ZjSnpYU2xFMm9RYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiOEZuaTZIZnpCVWYrQlYzRXU3eTNXenFqMk85NUFsdHZxNEt6S0FJcGFaMXM4NEVFTkZGeFJJYlpxL3p5alVZWjBrRVpQOEtiTGovNmxGNmphWVh0QUE9PSIsImRldmljZVNpZ25hdHVyZSI6IjNmaEVDSDFUWktmdXk0Rm1sVWltcXJkWURnNEZNMGdkbnZLc1Z6YWlPLzFseVNEaWs1SDUrN3dHWUhyWW1NMmVaVkdhSjZJYVFUaHUwYnB0bnJTNWdBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjI1ODgxNDU3MjI6MzVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVlJvLzcwZkVvdnZVWHlUWmhKV0IwOGJrc1U0TkE2NUgzQ2MxMHBSTnFFSCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjc4OTE3OCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFIai8ifQ==';

const prefix = process.env.PREFIX || .
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keutly';
const packname = process.env.PACKNAME || 'keutly';
const dev = process.env.DEV || '2250788145722';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEUETLY-MD';
const mode = process.env.MODE || 'privat';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
